value:
  user_size: 80
  user_page: 10
  maximum_name: 50
  maximum_email: 255
  maximum_pass: 6
  min_hours: 2
  maximum_micropost: 140
  micropost_user: 50
  microposts_size: 1
  size_img: 400
  per_page: 10
